align arguments with manubulon, use bash arrays properly

diff --git a/check_apc_pdu b/check_apc_pdu
--- a/check_apc_pdu
+++ b/check_apc_pdu
@@ -20,76 +20,90 @@
 name=$(basename "$0")
 usage="
 Usage:
-    $name -H <hostname> [-2] [-p <port>] [-C <community>] [-t transport] [-w <warning>] [-c <critical>] [-f] [-d]
-    $name -H <hostname> -3 -l <secName> [-t transport] [-L <protocolList>] [-x <authPassword>]
-        [-X <privPassword>] [-w <warning>] [-c <critical>] [-f] [-d]
+    $name -M <mode> -H <hostname> [-2] [-p <port>] [-C <community>] [-T transport] [-w <warning>] [-c <critical>]
+        [-t <timeout>] [-r <retry>] [-f] [-v]
+    $name -M <mode> -H <hostname> -l <secName> [-T transport] [-L <protocolList>] [-x <authPassword>]
+        [-X <privPassword>] [-w <warning>] [-c <critical>] [-t <timeout>] [-r <retry>] [-f] [-v]
     $name -h
 
+    -M mode             Polling mode (currently defaults to only supported value 'load')
     -H hostname         Hostname
     -p port             SNMP port
-    -C community        SNMP version 1/2c community (default public)
-    -2                  Use SNMP version 2c (default 1)
-    -3                  Use SNMP version 3 (default 1)
-    -t transport        SNMP transport (udp, tcp, udp6, tcp6; default udp)
+    -C community        SNMP version 1/2c community
+    -2                  Use SNMP version 2c (instead of 1)
+    -T transport        SNMP transport (udp, tcp, udp6, tcp6; default udp)
     -l secName          SNMP v3 username
-    -L protocolList     SNMP v3 authentication, privacy protocols (default md5,des)
+    -L protocolList     SNMP v3 authentication, privacy protocols (default sha,aes)
     -x authPassword     SNMP v3 authentication password
     -X privPassword     SNMP v3 privacy password
-    -w warning          Warning amperage threshold (specified in dA)
-    -c critical         Critical amperage threshold (specified in dA)
+    -w warning          Warning threshold for CPU (%) checks
+    -c critical         Critical threshold for CPU (%) checks
+    -t timeout          Timeout in seconds
+    -r retry            Retry count
     -f                  Output performance data
-    -d                  Output debug data
+    -v                  Be verbose on stderr
     -h                  Help (print command usage and quit)
 "
 
 # set some defaults
+mode="load" # may add more later?
 version="1"
-community="public"
+community=
 port="161"
-protocols="md5,des"
+protocols="sha,aes"
 transport="udp"
+snmp_opts=("-Oeqvu")
+message=""
+ext_message=""
 exit="0"
 generate_perf_data="0"
-debug="0"
+perf_data=""
+timeout=5
+retry=3
+debug=0
 snmpget="/usr/bin/snmpget"
-snmp_opts="-OeqvU"
-snmp_cmd=("$snmpget" "$snmp_opts")
+snmpwalk="/usr/bin/snmpwalk"
 warn_oid=".1.3.6.1.4.1.318.1.1.12.2.2.1.1.3.1"
 crit_oid=".1.3.6.1.4.1.318.1.1.12.2.2.1.1.4.1"
 
-while getopts "H:p:C:23l:L:x:X:w:c:fdh" option; do
+while getopts "M:H:p:C:2T:l:L:x:X:w:c:t:r:fvh" option; do
 	case $option in
+		M) mode=$OPTARG;;
 		H) hostname=$OPTARG;;
 		p) port=$OPTARG;;
-		2) version=2c;;
-		3) version=3;;
 		C) community=$OPTARG;;
+		2) version=2c;;
+		T) transport=$OPTARG;;
 		l) secName=$OPTARG;;
 		L) protocols=$OPTARG;;
 		x) authPassword=$OPTARG;;
 		X) privPassword=$OPTARG;;
 		w) warning=$OPTARG;;
 		c) critical=$OPTARG;;
+		t) timeout=$OPTARG;;
+		r) retry=$OPTARG;;
 		f) generate_perf_data=1;;
-		d) debug=1;;
-		h) echo "$usage" && exit 3;;
+		v) (( debug++ ));;
+		h) echo "$usage" && exit;;
+		*) echo "$usage" && exit 3;;
 	esac
 done
 
-if [[ -z "$hostname" ]]
-then
+if [[ -z "$hostname" ]] || [[ -z "$mode" ]]; then
 	echo "Unknown: Missing hostname or mode parameter"
 	echo "$usage"
 	exit 3
 fi
 
-if [[ "$version" = "3" ]]; then
+if [[ "$version" = "1" ]] && [[ -z "$community" ]]; then
+	# haven't specified v2c and no community, assume they want v3
 	if [[ -z "$secName" ]]; then
-		echo "Unknown: Missing SNMP v3 security name"
+		echo "Unknown: Missing SNMP v3 security name or v1 community name"
 		echo "$usage"
 		exit 3
 	fi
-	snmp_cmd=(${snmp_cmd[@]} "-v" "$version" "-u" "$secName")
+	version=3
+	snmp_opts+=("-v" "$version" "-u" "$secName")
 	if [[ -z "$authPassword" ]]; then
 		secLevel="NoAuthNoPriv"
 	else
@@ -99,34 +113,34 @@ if [[ "$version" = "3" ]]; then
 			secLevel="AuthNoPriv"
 		else
 			secLevel="AuthPriv"
-			snmp_cmd=(${snmp_cmd[@]} "-x" "$privProtocol" "-X" "$privPassword")
+			snmp_opts+=("-x" "$privProtocol" "-X" "$privPassword")
 		fi
-		snmp_cmd=(${snmp_cmd[@]} "-l" "$secLevel" "-a" "$authProtocol" "-A" "$authPassword")
+		snmp_opts+=("-l" "$secLevel" "-a" "$authProtocol" "-A" "$authPassword")
 	fi
-	snmp_cmd=(${snmp_cmd[@]} "$transport:$hostname:$port")
 else
 	if [[ -z "$community" ]]; then
 		echo "Unknown: Missing community parameter"
 		echo "$usage"
 		exit 3
 	fi
-	snmp_cmd=(${snmp_cmd[@]} "-v" "$version" "-c" "$community" "$transport:$hostname:$port")
+	snmp_opts+=("-v" "$version" "-c" "$community")
 fi
+snmp_opts+=("-t" "$timeout" "-r" "$retry" "$transport:$hostname:$port")
 
 
 if [[ ! $warning =~ ^[0-9]+$ ]] || [[ ! $critical =~ ^[0-9]+$ ]]; then
 	[[ $debug -gt 0 ]] && printf "No warning or critical threshold specified, fetching from device\n"
-	[[ $debug -gt 0 ]] && printf "Running command: %s %s %s\n" "${snmp_cmd[*]}" "$warn_oid" "$crit_oid"
-	read -d "\n" warning critical <<< $("${snmp_cmd[@]}" "$warn_oid" "$crit_oid" 2> /dev/null)
+	[[ $debug -gt 0 ]] && printf "Running command: %s %s %s %s\n" "$snmpget" "${snmp_opts[*]}" "$warn_oid" "$crit_oid"
+	read -d "\n" warning critical <<< $("$snmpget" "${snmp_opts[@]}" "$warn_oid" "$crit_oid" 2> /dev/null)
 	stat=$?
 	[[ $debug -gt 0 ]] && printf "Returned %d\n" $stat
 	[[ $debug -gt 0 ]] && printf "Retrieved warning and critical thresholds %d and %d via SNMP\n" "$warning" "$critical"
 fi
 
 if [[ $warning -lt 1 ]] || [[ $critical -lt 1 ]]; then
-       printf "Invalid warning (%d) or critical (%d) thresholds supplied or retrieved!\n" "$warning" "$critical"
-       echo "$usage"
-       exit 3
+	printf "Invalid warning (%d) or critical (%d) thresholds supplied or retrieved!\n" "$warning" "$critical"
+	echo "$usage"
+	exit 3
 fi
 
 # can't do bash math in case we get a float
@@ -135,8 +149,8 @@ read -d "\n" warn10 crit10 <<< $(echo "$warning * 10;$critical * 10" | bc)
 check_oid=".1.3.6.1.4.1.318.1.1.12.2.3.1.1.2.1"
 check_name="Load"
 check_unit="A"
-[[ $debug -gt 0 ]] && printf "Running command: %s %s\n" "${snmp_cmd[*]}" "$check_oid"
-metric=$("${snmp_cmd[@]}" "$check_oid" 2> /dev/null)
+[[ $debug -gt 0 ]] && printf "Running command: %s %s %s\n" "$snmpget" "${snmp_opts[*]}" "$check_oid"
+metric=$("$snmpget ${snmp_opts[@]}" "$check_oid" 2> /dev/null)
 stat=$?
 [[ $debug -gt 0 ]] && printf "Returned %d\n" $stat
 if [[ "$metric" =~ [^0-9] ]] || [[ -z "$metric" ]] || [[ $stat != 0 ]]; then
